version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/.venv
      - redis-data:/data/redis
    command: sleep infinity
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

volumes:
  redis-data:
