services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app
      - /app/.venv
      - redis-data:/data/redis
    command: sleep infinity
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

volumes:
  redis-data:
