apt_packages:
  - python3.12
  - python3.12-venv
  - python3-pip
  - python-is-python3
  - direnv
  - git
  - jq
  - gh
  - zsh
  - redis-server
  - supervisor

python:
  version: "3.12"
  venv_path: "/app/.venv"

redis:
  data_dir: "/data/redis"
  port: 6379
  daemonize: "yes"
  appendonly: "yes"
  maxmemory: "256mb"
  maxmemory_policy: "allkeys-lru"